name: Tests
on:
  push:
    branches:
      - main
      - '*.x'
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
  pull_request:
    branches:
      - main
      - '*.x'
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: '3.11', python: '3.11', tox: py311}
          - {name: 'Lowest', python: '3.11', tox: py311-lowest}
          - {name: '3.10', python: '3.10', tox: py310}
          - {name: '3.9', python: '3.9', tox: py39}
          - {name: '3.8', python: '3.8', tox: py38}
          - {name: '3.7', python: '3.7', tox: py37}
          - {name: 'Typing', python: '3.11', os: ubuntu-latest, tox: typing}
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: 'pdm.lock'
      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: ~/.cache/pdm
          key: ${{ matrix.python }}-pdm-${{ hashFiles('pdm.lock') }}
          restore-keys: ${{ matrix.python }}-pdm-
      - name: cache mypy
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: ./.mypy_cache
          key: mypy|${{ matrix.python }}|${{ hashFiles('pyproject.toml') }}
        if: matrix.tox == 'typing'
      - run: |
          pip install pdm
          pdm config install.cache true
          pdm sync -dG tox
      - run: pdm run tox -e ${{ matrix.tox }}
